# Generated by Django 3.0.6 on 2020-05-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_name',
        ),
    ]
